releases:


- name: grafana-playground-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
    name: grafana-playground-storage
  chart: ./charts/nfs-volume
  values:
  - grafana-playground/nfs-volume.yml

- name: grafana-playground
  namespace: monitoring
  labels:
    app: grafana
    group: monitoring
    name: grafana-playground
  chart: stable/grafana
  # Latest version has a bug https://github.com/kubernetes/charts/pull/6196
  version: 1.10.2
  values:
  - grafana-playground/grafana.yml
  - ../config/grafana-playground/grafana-secret.yml


- name: grafana-global-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
    name: grafana-global-storage
  chart: ./charts/nfs-volume
  values:
  - grafana-global/nfs-volume.yml

- name: grafana-global
  namespace: monitoring
  labels:
    app: grafana
    group: monitoring
    name: grafana-global
  chart: stable/grafana
  # Latest version has a bug https://github.com/kubernetes/charts/pull/6196
  version: 1.10.2
  values:
  - grafana-global/grafana.yml
  - ../config/grafana-global/grafana-secret.yml


- name: prometheus-k8s-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
    name: prometheus-k8s-storage
  chart: ./charts/nfs-volume
  values:
  - prometheus-k8s/nfs-volume.yml

- name: prometheus-k8s
  namespace: monitoring
  labels:
    app: prometheus
    group: monitoring
    name: prometheus-k8s
  chart: stable/prometheus
  # Latest version 6.7.4 requires Helm > 2.8
  version: 6.7.3
  values:
  - prometheus-k8s/prometheus.yml


- name: prometheus-global-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
    name: prometheus-global-storage
  chart: ./charts/nfs-volume
  values:
  - prometheus-global/nfs-volume.yml

- name: prometheus-global
  namespace: monitoring
  labels:
    app: prometheus
    group: monitoring
    name: prometheus-global
  chart: stable/prometheus
  # Latest version 6.7.4 requires Helm > 2.8
  version: 6.7.3
  values:
  - prometheus-global/prometheus.yml
  - ../config/prometheus-global/prometheus.yml
