alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false

server:
  baseURL: http://ome-lochy.openmicroscopy.org/prometheus-global
  prefixURL: /prometheus-global
  # Ingress is handled by oauth2-proxy
  persistentVolume:
    enabled: true
    existingClaim: prometheus-global-storage-nfs-volume
