---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nfs-volume.fullname" . }}
  labels:
    app: {{ template "nfs-volume.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
{{ toYaml .Values.accessModes | indent 4 }}
  capacity:
    storage: {{ .Values.size }}
  nfs:
    path: {{ .Values.nfs.parentpath }}/{{ required "NFS subdirectory share name required" .Values.name }}
    server: {{ .Values.nfs.server }}
